### PR TITLE
Added supprot for default(T) expression used in contracts.

### LINKED ISSUE #29: Malfromed Contract. Found Requires after assignment
After abbreviators [started to work](https://github.com/Microsoft/CodeContracts/issues/23), we get the error 
>Malfromed Contract. Found Requires after assignment.

for the following method:

```C#
[ContractAbbreviator]
[SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "value")]
[SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "userMessage")]
public static void NotDefault<T>(T value, string userMessage)
{
	Contract.Requires<ArgumentException>(!EqualityComparer<T>.Default.Equals(value, default(T)), userMessage);
}
```

If method's body is inlined as a usual CodeContract, or abbreviator is used within the same assembly no errors appear.

**Update**
This error occurs only for enum types.

### PR DESCRIPTION
**Pull request by hubuk**
I do not know how to run Foxtrot tests so it would be great if someone can take a look at DefaultExpression.cs test and confirm it is correct.
This should fix #29.

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
I'll test this. But actually running foxtrot tests is pretty simple: use a test explorer and click Run All for Foxtrot tests. Nothing more.

**Comment by hubuk** [comment]
Got it, thnaks. I will make sure that the test is correct.

**Comment by SergeyTeplyakov** [comment]
I assume tests are passing? In this case i'll merge the PR.

**Comment by hubuk** [comment]
I would love to check, but cannot build solution in VS2015. Also Build.bat reports errors on CodeTools. It was prebuilt previously. Lack of possibility to build the solution on VS2015 is by design or is it something with my VS installation?

**Comment by sharwell** [comment]
> Lack of possibility to build the solution on VS2015 is by design or is it something with my VS installation?

Neither. Some of the projects use a customized build process which is no longer supported in 2015. Right now Visual Studio 2013 is the only supported build and test environment, although you will still need .NET 4.6 installed on the build machine.

**Pull request closed without merging**
