### PR TITLE
Update imported CCI2 binaries

### PR DESCRIPTION
**Pull request by tom-englert**
This fixes issue #169 
This is not the optimal solution, but this bug is really blocking so I think we can't wait until there is an official release of CCI2.
See the comments in the commits for how this was done.

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
Will review this stuff this weekend.

**Comment by SergeyTeplyakov** [comment]
Any chances to add test case for this fix? Just curious, I know that in some cases this would be impossible/very complicated...

**Comment by tom-englert** [comment]
@SergeyTeplyakov adding test cases for this would require to setup the same complex harness as for the clousot tests. I added an issue for this ( #277), since we probably should not wait to fix #169 until we have this tests.

**Comment by tom-englert** [comment]
After Mike has updated the CCI2 sources I have rebuilt everything in a new branch to reduce the complexity of the PR, so this is replaced by  #276

**Pull request closed without merging**
