### PR TITLE
Bugs bug191

### PR DESCRIPTION
**Pull request by SergeyTeplyakov**

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
Folks, any comments? 
//cc: @fedotovalex

**Comment by hubuk** [comment]
I can confirm, the fix is working. Good job!
In addition this issue is also observable in Foxtrot\Foxtrot\Extraction\ExtractorVisitor.cs, so many tasts are failing in VS2015.

**Comment by hubuk** [comment]
The only place I would like to change is IsBaseContructorCall. This method returns true also when there is this() constructor call. Maybe rename it to IsChainContructorCall or something similar?

**Comment by SergeyTeplyakov** [comment]
@hubuk Sure, will rename it.

**Pull request merged**
