### PR TITLE
Enable automated execution of all unit tests in AppVeyor

### PR DESCRIPTION
**Pull request by asvishnyakov**
You need additional configure AppVeyor account with at least Basic plan (Free plan has a limits, what prevents test successful execution) to enable automated execution

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
Thanks a lot!

Just because static checker tests are taking so long, maybe for now we should disable them? Otherwise our merging process could be a bit painful... Or maybe we can annotate them based on duration? LongRun/ShortRun? Any ideas?

**Comment by asvishnyakov** [comment]
It depends on AppVeyor plan only. If you will use Free, you need disable it all. If you will use Basic, you don't need change anything.

**Comment by sharwell** [comment]
I have an AppVeyor Pro OSS subscription which I let multiple projects I'm involved with use, but there are a few challenges to enable it here.

1. I can't enable it for a repository in the Microsoft organization on GitHub. It would need to move to dotnet or another organization before it's even possible.
2. This build is slow, and active involvement by the community would cause QOS problems for other projects that currently have short builds.

My hope was that Microsoft would pay for an AppVeyor Pro OSS subscription dedicated to this project.

**Comment by asvishnyakov** [comment]
@sharwell So, only organizational issues prevents you to enable CI testing, right?

**Comment by sharwell** [comment]
@asvishnyakov It's organizational and pricing. Currently I donate $300-$360/year for CI services on projects like [StyleCop Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers). The build for this repository is particularly resource intensive, so it's likely I would need to add a additional concurrent job to bring it into my account, which would raise my cost to $500-$600/year.

**Comment by SergeyTeplyakov** [comment]
Guys, before we moved to dotnet org, I'll try to get basic appveyor plan that Microsoft will pay for. I hope to get an approval for this plan as soon as posible to finish the automation.

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov  Hmmm, looks like you enable AppVeyor builds for FoxtrotTests and UnitTests. Please, merge 8f344cb96e78abae8b6634fee0e58b8b46caf459 commit by @sharwell, even you don't want enable all test (by merge this pr)

**Comment by SergeyTeplyakov** [comment]
@asvishnyakov I'm working on getting new plan. But I think they should fit into 1hr limit.

BTW, can I just accept this PR instead of merging one commit?

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov Yes, you can. But it enable all tests, include Clousot, which before was disabled.
I don't how it can fit into 1hr limit without new plan. With new plan it will fit 30 min limit

**Comment by SergeyTeplyakov** [comment]
@asvishnyakov Time difference is tricky. Already merged. Will create a pull request that will disable Clousot tests until I'll get an approval for Basic plan.

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov I think no only Clousot, but Foxtrot too - it's failed because of time limit too

**Comment by SergeyTeplyakov** [comment]
I hope to leave them, otherwise appveyor would test only compilation... :(

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov How about UnitTests?

**Comment by SergeyTeplyakov** [comment]
We can turn them on. At least part of stuff will be running...
But can you try to turn Foxtrot back on? Is it 100% that it would be not enough time just for them?

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov Yep, just see your CodeContracts builds on AppVeyor they all was failed in 59m:59s-1hr because of Foxtrot test. We may enable it, but only part of Foxtrot tests running and no one of UnitTests. [For example](https://ci.appveyor.com/project/SergeyTeplyakov/codecontracts/build/1.9.10122.11/tests) (before my PR merged)

**Comment by SergeyTeplyakov** [comment]
Good news everyone. We do have 1 year pro subscription!

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov Uncomment 13, 15 and 16 lines in AppVeyor.yml

**Comment by SergeyTeplyakov** [comment]
Done: #369

**Pull request merged**
