### PR TITLE
Fixed path to Microsoft.CodeContractAnalysis.targets for MSBuild v12.0.

### PR DESCRIPTION
**Pull request by hubuk**
Change requested in #30 "MSBuild 12.0 Microsoft.CodeContracts.targets imports wrong ContractAnalysis.targets"

### CODE REVIEW

**Comment by sharwell** [comment]
:+1: This addresses the *bug* identified in #30.

:bulb: I highly recommend creating a new issue to address the sub-optimal paths used for this property. This enhancement was mentioned in #30 and applies to each of the targets files for the various MSBuild versions.

**Comment by hubuk** [comment]
I will do a rework and propose a complete solution.

**Comment by sharwell** [comment]
@hubuk By the way, in case you are not familiar, you can see an overview of the emoji I use in comments and their meaning [on this page](https://github.com/openstacknetsdk/openstack.net/blob/master/CONTRIBUTING.md#emoji).

**Comment by hubuk** [comment]
The change should be simple and will reduce duplicated content to maintain. I think that creating additional issue is an unnecessary overhead.

**Pull request merged**
