### PR TITLE
Enable foxtrot and clousot tests.

### PR DESCRIPTION
**Pull request by SergeyTeplyakov**

### CODE REVIEW

**Comment by asvishnyakov** [comment]
Failed because of time limit. F**k!

**Comment by SergeyTeplyakov** [comment]
Yeah. I'm trying to disable static checker tests...

**Comment by asvishnyakov** [comment]
I'm successfully run Foxtrot and Clousot tests in Pro trial. But we enable UnitTests too. I try to found longest tests or profile its to make possible run all test without exceeding time limit

**Comment by SergeyTeplyakov** [comment]
In the report I saw couple of tests that took more than a minute, but there is only few of them. We can use that report and disable some long running tests...

**Comment by SergeyTeplyakov** [comment]
Based on the current trend, we'll not be able to turn static checker tests back...
just foxtrot tests will take more than half an hour...

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov 697 test longer than 1 sec, 198 tests longer than 5 sec, 68 test longer than 6 sec, 30 tests longer than 7 sec, 14 tests longer than 8 sec.

**Comment by SergeyTeplyakov** [comment]
@asvishnyakov Did you check this on your machine? Because I saw few tests that took more than a minute on appveryor machine...

**Comment by SergeyTeplyakov** [comment]
Ok, I'll merge with enabled foxtrot tests and then we'll see what we can do with static checker.

**Comment by asvishnyakov** [comment]
@SergeyTeplyakov No, I didn't build CC on my machine. Now I'm installing VS2013 and try to profile tests. And yep, at least 5 tests longer than 1 minute.

**Comment by SergeyTeplyakov** [comment]
Closing this PR. Need to fine tune clousot tests before turning them off..

**Pull request closed without merging**
