### PR TITLE
Fix MSBuild 14 path to sn.exe

### PR DESCRIPTION
**Pull request by yaakov-h**
Fix for #179 (and maybe #160?).

### CODE REVIEW

**Comment by sharwell** [comment]
I believe this works on some systems but not others.

I need to do a bit more investigating.

**Comment by yaakov-h** [comment]
Alright.

**Comment by SergeyTeplyakov** [comment]
Currently Roslyn is using the same targets: https://github.com/dotnet/roslyn/blob/9362f37f29898abd5bd4f0e6be127ab7a947a806/build/Targets/VSL.Settings.targets#L233

And I thought that the second line should be valid only in the rare cases. But I agree with @sharwell this fix would be partial as well: it will work in one configurations but not work in the others.

**Comment by yaakov-h** [comment]
What configurations would have MSBuild 14.0 without Windows SDK 10.0A? Visual Studio 2015 provides both, as best I can tell, and on my Windows 8.1 machine with VS2008, VS2013 and VS2015, only Windows SDK 10.0A has .NET 4.6 Tools.

I'll have to investigate further why `$(TargetFrameworkSDKToolsDirectory)` isn't being used in my case, but if I build a dummy project with `msbuild` and `/v:diag`, the following line appears in the output:

    TargetFrameworkSDKToolsDirectory = C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\

**Comment by sharwell** [comment]
I checked this on a Windows 10 machine and a Windows 7 machine, and found that with Visual Studio 2015 RTM a copy of **sn.exe** was located as specified in this pull request. I haven't verified the location on AppVeyor, but based on the results so far I'm ready to :+1: this pull request.

**Comment by yaakov-h** [comment]
Just following up here - @SergeyTeplyakov, can you specify any configurations where this would not work, or is this OK?

**Comment by SergeyTeplyakov** [comment]
@yaakov-h I'll check on my working machine later today.

**Comment by yaakov-h** [comment]
As opposed to your broken machine? :)

**Comment by SergeyTeplyakov** [comment]
Yep. I've checked my Windows 8.1 machine and sn is located in the place specified by the PR.

Merging....

**Pull request merged**
