### PR TITLE
Replaced calls to UpdateManifestVersion with XmlPoke

### LINKED ISSUE #34: Missing UpdateManifestVersion.exe
Its not possible to build the setup by running buildCC as it expects the executable UpdateManifestVersion.exe to exist in Microsoft.Research\common\bin.

### PR DESCRIPTION
**Pull request by hubuk**
Recreated missing UpdateManifestVersion console application project. The root cause was a missing exclusion from .gitignore file.
This should fix #34

### CODE REVIEW

**Comment by sharwell** [comment]
:exclamation: I think this should be updated to build the new project as part of the build script, and continue to exclude the compiled binary from source control.

**Comment by sharwell** [comment]
:exclamation: The build script should not be directly modifying files which live in source control. Eventually this build step will need to be replaced by either a build step that copies the file to the intermediate output directory and applies the transformation there, or moved to be a separate process which is executed to update version numbers on-demand when official releases are made.

**Comment by hubuk** [comment]
To be closed/modified. Will check if XmlPoke task can be used instead of an executable file.

**Comment by hubuk** [comment]
Should fix issue #34.

Main weaknesses in original approach but not addressed in this PR are:
1. Version numbers are modified in place. There is no copy-to-temporary-location-and-change approach. This issue should be addressed in #65.
2. Number of vsixmanifest files should be reduced to one in most optimistic scenario. Probably will be covered in a solution for #17 or #65.

**Comment by sharwell** [comment]
Yes, my solution for the VSIX distribution only uses one vsixmanifest file.

**Comment by sharwell** [comment]
This is an obviously superior strategy to the previous executable. Good job on that.

My only real question is whether we want to wait for me to finish refactoring the VSIX or not. It shouldn't be too much more work.

**Comment by hubuk** [comment]
I can surely wait. What would be the best way to do that? Closing this PR for now and reopen it in slightly modified form after your changes?

**Comment by sharwell** [comment]
That works for me :)

**Comment by hubuk** [comment]
Great. I am freezing it for now.

**Comment by mike-barnett** [comment]
Thanks so much! This is really great. You are all doing an amazing job getting this code base into shape. I can't tell you how much I appreciate it.

**Pull request closed without merging**
