### PR TITLE
Fix for #172.

### LINKED ISSUE #172: CC1099: Contract extraction failed: async/iterator issue in async without await
I am getting the error `CC1099` on a particular method.  I have narrowed the method down to one specific change which will cause the failure.  The below sample compiled as a console application with rewriting enabled seems to reliably fail.

Error:
> EXEC : error CC1099: Contract extraction failed: async/iterator issue: In method EmptyAsyncTest.Program.Foo, assembly EmptyAsyncTest\EmptyAsyncTest\obj\Debug\EmptyAsyncTest.exe

Code:

    using System;
    using System.Threading.Tasks;

    namespace EmptyAsyncTest
    {
        class Program
        {
            static void Main(string[] args)
            {
            }

            async Task Foo()
            {
                if (DateTime.Now.Day == 0 && 1 == 2)
                {
                }
            }
        }
    }

The following variations do not trigger the bug:
 - Removing `async` and returning `Task.FromResult(false)`
 - Removing `&& 1 == 2`
 - Removing `DateTime.Now.Day == 0`
 - Adding `await Task.Delay(1)`

Environment:
VS 2015 CTP, Code Contracts 1.9.10714.2, Windows 8.1, Project is .Net 4.5, Only rewriting is enabled
Also repro'd by compiling fe3bf15c36923ebb833087d8c8781ce2ae60e6ce and running `foxtrot`.  Same output.

### PR DESCRIPTION
**Pull request by SergeyTeplyakov**
This change fixes #172.

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
Gentle ping for code review...

**Comment by sharwell** [comment]
:+1: (Assuming the test passes)

**Comment by SergeyTeplyakov** [comment]
Yep, tests (new and old ones) are good.

**Comment by nparrish** [comment]
Do you have an estimate on when a new release with this fix will be published?

**Comment by jholovacs** [comment]
yikes this just killed my build.  Is this released?

**Comment by sampa999** [comment]
Is this going to be released soon?

**Pull request merged**
