### PR TITLE
Issue148 preparation

### PR DESCRIPTION
**Pull request by tom-englert**
Reformatted some of the code in the regression test area. 
No semantic changes.

### CODE REVIEW

**Comment by tom-englert** [comment]
Intersects with #151

**Comment by sharwell** [comment]
@tom-englert Do you mind if I do the initial formatting the same way as the other open pull requests for reformatting? I could do it right now if you want.

**Comment by tom-englert** [comment]
@sharwell I just did this minor reformatting to ease my life - once all the other reformatting changes are pulled into master I can adapt my changes to match the new style before this one gets actually pulled.

**Comment by sharwell** [comment]
@tom-englert The pull requests to reformat this code are #152, #153, and #154. The biggest difference is the commits that actually do the format operation are marked as being authored by @FrancescoLogozzo so it doesn't change the author of the entire code base according to git blame.

**Comment by tom-englert** [comment]
this one is anyhow closed, I have marked #151 to stay until the reformatting is done.

**Pull request closed without merging**
