### PR TITLE
Add null check to avoid crash when parsing Roslyn generated code.

### PR DESCRIPTION
**Pull request by tom-englert**
To fix https://github.com/Microsoft/CodeContracts/issues/366

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
Just in case: any chances to add test case for this?

**Comment by SergeyTeplyakov** [comment]
From #366 comment I see that this fix is kind of short-term one. If this is true, I would suggest to put a comment that explains this in the code with (maybe) todo to fix this later properly.

**Comment by tom-englert** [comment]
Yes, this is not a final fix and should not close #366. It just avoids the crash, but now the output is ugly. However without this it's totally unusable due to the crash.
More details to be found in #366.

**Comment by tom-englert** [comment]
About testing: Currently we have no framework for CCDoc tests (#277). Also we do not test Clousot/cccheck with the 4.5 framework/compiler. (#373)

**Pull request merged**
