### PR TITLE
Reformat code in CodeAnalysis

### PR DESCRIPTION
**Pull request by sharwell**
This reformat operation used dotnet/codeformatter@1d719e4e with `/rule-:FieldNames`.

### CODE REVIEW

**Comment by SergeyTeplyakov** [comment]
This PR is out of date alredy, so I don't know what the easiest way to deal with: rebase or just close this one and reformat new stuff? @sharwell

**Comment by sharwell** [comment]
@SergeyTeplyakov I'll update any formatting PRs that get out of date. Just let me know if/when you see them. :smile:

**Comment by SergeyTeplyakov** [comment]
I'm OK to merge all of them today.

**Comment by SergeyTeplyakov** [comment]
I think the only remaining are this one and #124.

**Comment by sharwell** [comment]
@SergeyTeplyakov I updated this pull request.

**Pull request merged**
